---
- name: Create VM from Vcenter Template
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    vm_name: "vm-teste"
    hostname: "192.168.22.50"
    username: "strindade"
    password: "130395Tary@"
  tasks:
    - name: Clone Template to New Virtual Machine
      community.vmware.vmware_guest:
        name: "{{ vm_name }}"
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: false
        template: rhel8 # Input vCenter Template
        datacenter: Datacenter # Input vCenter Datacenter
        resource_pool: # Input Resource Pool
        folder: "/"
        state: poweredon
        wait_for_ip_address: true

- name: Set VM IP and Hostname
  hosts: 192.168.26.85 # This is the IP that is set for the template, if you use a different IP update here.
  tasks:
    - name: Update IP
      ansible.builtin.lineinfile:
        path: /etc/sysconfig/network-scripts/ifcfg-ens192
        regex: "IPADDR=192.168.26.85" # Set to same IP as line 19
        line: "IPADDR={{ new_IP }}"

    - name: Update Hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}.domain.local" # Update domain

    - name: Reboot
      ansible.builtin.command: "init 6"
      ignore_errors: true

    - name: Pause for 30 seconds to wait for reboot
      ansible.builtin.pause:
        seconds: "10"
